### ISSUE TITLE
Meta issue: Top priority tasks

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-fathead#571]
Below are current issues that would have the most impact, i.e. working on them would enable Instant Answers to appear for more programming search queries on [DuckDuckGo](https://duckduckgo.com):

- [X] <strike>[jQuery: add redirects](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/516)</strike>
- [X] <strike>[MDN JS: add categories](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/528)</strike>
- [X] <strike>[MDN JS: add disambiguations for error types](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/529)</strike>
- [X] <strike>[MDN JS: show the first example in the article](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/530)</strike>
- [X] <strike>[Python: Separate Python2 only articles into new Python2 Fathead](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/555)</strike>
- [X] <strike>[MDN JavaScript: "data type" articles should have redirects with "type" and "data type" postfixed](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/556)</strike>
- [X] <strike>[Perl: Create New PerlPackageDoc FatHead](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/569)</strike>
- [X] <strike>[Python: Improve Django Fathead (or Create new Fathead) to cover more documentation](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/552)</strike>
- [X] <strike>[Python: Create New PEP Fathead](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/540)</strike>
- [X] <strike>[jQuery: Add article aliases (redirects) -- Event Methods](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/611)</strike>
- [X] <strike>[jQuery: Add article aliases (redirects) -- Add, set](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/609)</strike>
- [X] <strike>[jQuery: Add article aliases (redirects) -- Example](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/613)</strike>
- [ ] [MDN JS: Include uncategorized articles in the Instant Answer result](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/334)

@duckduckgo/duckduckhack-contributors Would you like to have a go at any of the open ones?

For the full list of Programming Mission issues, see the [combined DuckDuckHack task list](https://duckduckhack.com/issues).

**Comment by tagawa** [comment]
Just added some more high priority tasks to the list above.

**Comment by pjhampton** [comment]
Closing in favor of #747. The last issue is referenced there 😄
