### ISSUE TITLE
Meta issue: Beginner-friendly tasks

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-fathead#572]
Below are current issues that are relatively easy to work on but would still have a big impact, i.e. working on them would enable Instant Answers to appear for more programming search queries on [DuckDuckGo](https://duckduckgo.com):

- [X] <strike>[NodeJS: add common redirects (aliases)](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/513)</strike>
- [X] <strike>[PHP: add coverage data](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/521)</strike>
- [X] <strike>[Python: add coverage data](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/522)</strike>
- [X] <strike>[Apple Docs macOS: broaden search results by adding article aliases (redirects)](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/502)</strike>
- [X] <strike>[Can I Use: Broaden search results by adding more aliases](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/172)</strike>
- [X] <strike>[React API Docs: Broaden search results by adding more aliases](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/597)</strike>
- [X] <strike>[jQuery: Add article aliases (redirects) -- Event Methods](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/611)</strike>
- [X] <strike>[NodeJS: add coverage data](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/515)</strike>
- [X] <strike>[jQuery: Add article aliases (redirects) -- Add, set](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/609)</strike>
- [X] <strike>[jQuery: Add article aliases (redirects) -- Example](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/613)</strike>

@duckduckgo/duckduckhack-contributors Would you like to have a go at any of the open ones? They're beginner-friendly but you don't have to be a beginner!

For the full list of Programming Mission issues, see the [combined DuckDuckHack task list](https://duckduckhack.com/issues).

**Comment by anjanjr** [comment]
@tagawa i was thinking on working on #172. on the issues pages **ppython** suggested to use regex for the alias part, would that work? If yes i can start working on it, or type out all the aliases as suggested by @moollaza.

**Comment by tagawa** [comment]
Hi @anjanjr! Thank you very much for offering to help. At the moment we don't have the backend support to work with regex in the text files, so please could we use keywords only for now?

**Comment by anjanjr** [comment]
@tagawa Yeah, Okay! will add keywords for now, and you're welcome, am very happy to help.
I have a question, I suppose all the lines in https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/caniuse/articles.txt do not need aliases. wherever there is a requirement, we have to add keywords only for those lines, right? I mean the *redirects.txt* file doesnot have to contain all the lines that are present in https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/caniuse/articles.txt

**Comment by tagawa** [comment]
@anjanjr That's right - everything in `articles.txt` is already covered. For example,  the query `css3 opacity` has an article that appears in the IA (Instant Answer) but we could add a redirect to it for the query `css3 transparency`.
