### ISSUE TITLE
Ruby: Improve Reference Coverage (Stdlib)

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#706]
# Description

Currently, the [Ruby Docs Fathead](https://duck.co/ia/view/ruby) is only parsing the [Ruby Core documentation](http://ruby-doc.org/core-2.4.0/) and has left out the [Stdlib documentation](http://ruby-doc.org/stdlib-2.4.0/). This means that some developers are missing out on an IA. For example: 

**Core: Ruby Time** 👍 

![screen shot 2017-01-23 at 6 19 47 pm](https://cloud.githubusercontent.com/assets/8960296/22216873/ab036566-e198-11e6-9fec-38a143513749.png)

**Stdlib: Ruby Date** 👎 

![screen shot 2017-01-23 at 6 19 33 pm](https://cloud.githubusercontent.com/assets/8960296/22216875/ad866bc6-e198-11e6-8016-656177a6eb35.png)

## Task

Update or extend parser to parse the stdlib docs. 

## Future Steps

Update the redirects.

## People to notify
@kotoshenya (Language Leader)

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/ruby

**Comment by acflint** [comment]
I'd be happy to take a crack at this. Anyone else who is interested, please get in touch! I'm new to Ruby so help is appreciated 👍

**Comment by pjhampton** [comment]
Thanks @acflint! You rock! 🤘 
Consider joining the DDG Github org so I can assign you to the issue: https://github.com/duckduckgo/duckduckgo/issues/182

**Comment by Dgibbins** [comment]
Hey all, will be helping acflint with this, would anyone be able to recommend some good Nokogiri references?

**Comment by acflint** [comment]
We think this is done, but @kotoshenya is going to look it over before we submit. If anyone else is interested, we welcome your feedback! https://github.com/acflint/stdlib

**Comment by pjhampton** [comment]
Thanks @acflint! 😄 
Sorry, I'm only getting round to this now! Did you submit a PR?

**Comment by acflint** [comment]
Yes I did! Thanks PJ :)

--
Alex
