### ISSUE TITLE
Meta issue: High Value Tasks

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#747]
The below issues have been created based on relevant search data. Development on these potentially high impact issues would enable Instant Answers to appear for more programming search queries on [DuckDuckGo](https://duckduckgo.com):

### Existing IAs to be Improved

- **High Impact** (These are the most important issues!)
  - [x] ~~[Node.js: Improve Descriptions](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/840)~~ - Thanks to @Lord-Lavios
  -  [x] ~~[Finish New Android Docs IA](https://github.com/duckduckgo/zeroclickinfo-fathead/pull/475)~~ - Thanks to @BillyBarbaro

- **Low Hanging Fruit**
  - [x] ~~[Bower: List all topic titles and language features to help measure coverage](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/784)~~ Thanks to @adityatandon007
  - [x] ~~[Django Suggestion: Extend parser to include submodules + meth
ods](htts://github.com/duckduckgo/zeroclickinfo-fathead/issues/766)~~ - Thanks to @Hestben!
  - [x] ~~[Spark Suggestion: Add Redirects](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/788)~~ - Thanks to @adityatandon007 
  - [x] ~~[ESLint: Add Descriptions](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/822)~~ - Thanks to @zodiac403
  - [x] ~~[Python Suggestion: Improve Coverage with further redirects](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/765)~~ - Thanks to @mustang25
  - [x] ~~[Flask Suggestion: Add Redirects](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/817)~~ - Thanks to @shanmbic 
  - [x] ~~[Scipy Suggestion: Increased Redirects](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/841)~~ - Thanks to @ashishbhate 
  - [x] ~~[Six Suggestion: Generate redirects for methods / functions](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/819)~~ Thanks to @BillyBarbaro 
  - [x] ~~[Pip Suggestion: Remove command keyword](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/818)~~ - Thanks to @BillyBarbaro 
  - [x] ~~[Spring Suggestion: Add Redirects (Split Casing)](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/789)~~ - Thanks to @BillyBarbaro 
  - [x] ~~[Angularjs (1.x) Suggestion: Add further redirect ](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/755)~~ - Thanks to @adityatandon007 
  - [x] ~~[Numpy: Modify Redirects](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/751)~~ Thanks to @adityatandon007
  - [x] ~~[Ruby: Add Ruby Coverage](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/733)~~ - Thanks to @acflint 
  - [x] ~~[JS: Add NPM CLI Coverage](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/736)~~ - Thanks to @JelaniThompson 
  - [x] ~~[NodeJS: List all topic titles and language features to help measure coverage](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/515)~~ - Thanks to @VirgaSenis
  - [x] ~~[SQLAlchemy: List all topic titles and language features](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/735#issuecomment-278200268)~~ - Thanks to @knowledgewarrior
  - [x] ~~[Swift Docs: List all topic titles and language](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/509)~~ - Thanks to @altern8tif 
  - [x] ~~[React.js Suggestion: Improve Redirects](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/758)~~ - Thanks to @Hestben 
  - [x] ~~[MDN CSS: HTML `<code>` blocks are stripped from result](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/722)~~
  - [x] ~~[MDN CSS: Add aliases (redirects) - list values](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/638)~~ - Thanks to @VirgaSenis 

@duckduckgo/duckduckhack-contributors Would you like to have a go at any of the open ones? Some are beginner-friendly but you don't have to be a beginner!

For the full list of Programming Mission issues, see the [combined DuckDuckHack task list](https://duckduckhack.com/issues).

**Comment by pjhampton** [comment]
Closing as we're reshifting our focus to improve existing IAs! 
See these for more info:

- **Goodies:** https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3971
- **Spice:** https://github.com/duckduckgo/zeroclickinfo-spice/issues/3162
